services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # RabbitMQ AMQP
      - "15672:15672" # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  mysql:
    image: mysql:8
    container_name: mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: APIWorker
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  api:
    build:
      context: .
      dockerfile: dockerfile.api
    depends_on:
      - rabbitmq
    ports:
      - "5000:5000"
    environment:
      RABBITMQ:Host: rabbitmq
      RABBITMQ:User: user
      RABBITMQ:Password: password
      DATABASE:Host: mysql
      DATABASE:Name: APIWorker
      DATABASE:User: myuser
      DATABASE:Password: mypassword
  worker:
    build:
      context: .
      dockerfile: dockerfile.worker
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ:Host: rabbitmq
      RABBITMQ:User: user
      RABBITMQ:Password: password
      DATABASE:Host: mysql
      DATABASE:Name: APIWorker
      DATABASE:User: myuser
      DATABASE:Password: mypassword

volumes:   
  mysql_data: